### ISSUE TITLE
Canvas Quality

### ISSUE THREAD

**Issue by chetweewax** [stomita/ios-imagefile-megapixel#19]
When the image is rendered to the canvas, is there a way to adjust the quality like rendering to the image.  I added the quality: 0.5, to the megapix.js (mpImg.render(resCanvas1, { maxWidth: 300, maxHeight: 300, quality: 0.5 });) but it does not change.  I ask because I am using .toDataURL("image/jpeg") to send the canvas to my php page to save on my server.

**Comment by BlackBanner** [comment]
Hi,

What would be the best optimised quality value?
Actually i have set mine as 0.5 and width of image rendered is 590px; Yet the image seems a bit noisy.
